apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ztt9na88e-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ztt9na88e-python 
  name: ztt9na88e-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ztt9na88e-python 
